### ISSUE TITLE
Allow user to configure mappings from message type to topic name and schema 

### ISSUE THREAD

**Issue by onobc** [spring-projects-experimental/spring-pulsar#269]
Consider the following code[^1]: 

```java
@Autowired PulsarTemplate<Type1> template1;
@Autowired PulsarTemplate<Type2> template2;

void send1(...) {
  template1.setSchema(Schema.JSON(Type1));
  template1.send("topic-1", new Type1());
}

void send2(...) {
  template2.setSchema(Schema.JSON(Type2));
  template2.send("topic-2", new Type2());
}
```

It would be convenient for the user to be able to configure a mapping between message types to schema and topics to use. Something like:
```yaml
spring.pulsar.producer.topic-mappings:
  acme.Type1: "topic1"
  acme.Type2: "topic2"

spring.pulsar.producer.schema-mappings:
  acme.Type1: SchemaType.JSON(acme.Type1)
  acme.Type2: SchemaType.JSON(acme.Type2)
```

This would reduce the boilerplate - such as:
```java
@Autowired PulsarTemplate<Type1> template1;
@Autowired PulsarTemplate<Type2> template2;

void send1(...) {
  template1.send(new Type1());
}

void send2(...) {
  template2.send(new Type2());
}
```

[^1]: https://stackoverflow.com/questions/75023746/defining-multiple-pulsar-producers-in-spring-boot-application

**Comment by gootik** [comment]
Some extra information on my setup right now. So far I've managed to reduce a little bit of the repetition by creating specific PulsarTemplate beans. This at least solves the schema issue, but I'm not entirely sure how this will play with caching. I believe this will be fine since only one `CachingPulsarProducerFactory` is auto generated. 

But this can't be taken further since we can't force the factory to use a specific topic.

```
@Configuration
public class MessageQueueConfig {
  @Bean
  public PulsarTemplate<Type1> createAccountActivityTemplate(PulsarProducerFactory<Type1> factory) {

    var template = new PulsarTemplate<>(factory);
    template.setSchema(Schema.JSON(Type1.class));

    return template;
  }

  @Bean
  public PulsarTemplate<Type2> createAccountActivityTemplate(PulsarProducerFactory<Type2> factory) {

    var template = new PulsarTemplate<>(factory);
    template.setSchema(Schema.JSON(Type2.class));

    return template;
  }
```

**Comment by onobc** [comment]
Hi @gootik ,
The topic-side of the equation is in main branch now as well. 

You can see how to use it here: https://docs.spring.io/spring-pulsar/docs/current-SNAPSHOT/reference/html/#_message_type_default

You can now do this: 
```java
@Autowired PulsarTemplate<Type1> template1;
@Autowired PulsarTemplate<Type2> template2;

void send1(...) {
  template1.send(new Type1());
}

void send2(...) {
  template2.send(new Type2());
}
```

With this in your `application.yml`:
```yaml
spring:
  pulsar:
    defaults:
      type-mappings:
        - message-type: com.acme.Type1
          topic-name: topic1
        - message-type: com.acme.Type2
          topic-name: topic2
```

and configuring in a customizer such as:
```java
@Bean
SchemaResolverCustomizer<DefaultSchemaResolver> customSchemaMappings() {
	return (schemaResolver) -> {
		schemaResolver.addCustomSchemaMapping(Type1.class, Schema.JSON(Type1.class));
		schemaResolver.addCustomSchemaMapping(Type2.class, Schema.JSON(Type2.class));
	};
}
```

In going through this process I figured out a clean way that I can add the schema mappings to the config props so that it can all be done in the yml conveniently, but I ran out of time. Will add that improvement as time permits.
