### ISSUE TITLE
PHASE 1: Make client authentication simpler

### ISSUE THREAD

**Issue by onobc** [spring-projects-experimental/spring-pulsar#95]
Typically, client authentication is configured by invoking the `authentication` method on the client builder and passing in the required info - for example:
```java
URL issuerUrl = new URL("https://auth.server.cloud/");
URL credentialsUrl = new URL("file:///path/to/KeyFile.json");
String audience = "urn:sn:acme:dev:my-instance";

PulsarClient client = PulsarClient.builder()
    .serviceUrl("pulsar://broker.example.com:6650/")
    .authentication(
        AuthenticationFactoryOAuth2.clientCredentials(issuerUrl, credentialsUrl, audience))
    .build();
```

However, the only current exposed mechanism to configure client authentication is via setting the `spring.pulsar.client.auth-*` properties. Moreover, to configure [oauth 2.0 access tokens](https://pulsar.apache.org/docs/2.10.1/security-oauth2/#java) based auth, the `spring.pulsar.client.auth-params` property must be set to a JSON string of all of the required values. It is cumbersome. 

```yaml
spring:
  pulsar:
    client:
      auth-plugin-class-name: org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2
      #auth-params-map.issuer-url: https://auth.server.cloud/
      #auth-params-map.private-key: file:///Users/some-key.json
      #auth-params-map.audience: urn:sn:acme:dev:my-instance
      auth-params: "{\"privateKey\":\"file:///Users/some-key.json\",\"issuerUrl\":\"https://auth.server.cloud/", \"audience\":\"urn:sn:acme:dev:my-instance"}"
```

We want to improve DXP in this area by allowing users to configure the simpler `spring.pulsar.client.auth-params-map.*` properties OR if they so choose, the more complicated `spring.pulsar.client.auth-params` property. Rather than simply pass these properties down into the client builder we will instead use them to directly call the `authentication` method during auto-configuration. 

**NOTE:** 
We should probably remove the properties from the map before passing them down into the client builder to avoid the builder to attempt to do the same auth logic. However, it may check if the auth is not null before doing anything. Need to look into this,

**Comment by alpreu** [comment]
I believe it's a good idea to remove `auth-params-map` completely as it's basically deprecated and some of the newer `Authentication` classes do not even implement this code path anymore. 
Auto-creating the `Authentication` object and passing it into the builder sounds like a good idea. 
We could add the config params for example as `spring.pulsar.client.authentication.*` to differentiate from the `auth-params-map`.

**Comment by onobc** [comment]
Be sure that we can handle the 3 [currently supported authentication types](https://pulsar.apache.org/docs/next/client-libraries-java#authentication)
* [TLS](https://pulsar.apache.org/docs/next/security-tls-authentication)
* [Athenz](https://pulsar.apache.org/docs/next/security-athenz)
* [Oauth2](https://pulsar.apache.org/docs/next/security-oauth2)

**Comment by onobc** [comment]
## Phase I

Support only property-based auth but ease the user's configuration burden and provide docs on exactly what to set for each auth type. 

Property-based auth does not work when using the `authParamsMap`. It does work when using the `authParams` JSON string. 
However, one problem w/ `authParams` is that it cumbersome and error prone for a human to craft a JSON string w/ a set of key value properties (possible but not a good DXP). Let's take the `authParamsMap` and create the `authParams` JSON string behind the scenes. 

Let's also provide docs on exactly what users need to set for each type of auth. 


### Auth Properties by Auth Type

* LEGEND: `a12n == authentication`

#### TLS

```yaml
spring.pulsar.client.auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationTls
spring.pulsar.client.auth-params-map.tlsCertFile: ...
spring.pulsar.client.auth-params-map.tlsKeyFile: ...
spring.pulsar.client.tlsTrustCertsFile: ...
spring.pulsar.client.enableTls: ...
```

#### Athenz

```yaml
spring.pulsar.client.auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationAthenz
spring.pulsar.client.auth-params-map.tenantDomain: ...
spring.pulsar.client.auth-params-map.tenantService: ...
spring.pulsar.client.auth-params-map.providerDomain: ...
spring.pulsar.client.auth-params-map.privateKey: ...
spring.pulsar.client.auth-params-map.keyId: ...
spring.pulsar.client.tlsTrustCertsFile: ...
spring.pulsar.client.enableTls: ...
```

#### Kerberos

```yaml
spring.pulsar.client.auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationSasl
spring.pulsar.client.auth-params-map.saslJaasClientSectionName: ...
spring.pulsar.client.auth-params-map.serverType: ...
```

#### OAuth2

```yaml
spring.pulsar.client.auth-plugin-class-name: org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2
spring.pulsar.client.auth-params-map.privateKey: ...
spring.pulsar.client.auth-params-map.issuerUrl: ...
spring.pulsar.client.auth-params-map.audience: ...
```

#### Http Basic

```yaml
spring.pulsar.client.auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationBasic
spring.pulsar.client.auth-params-map.user-id: foo
spring.pulsar.client.auth-params-map.password: bar
```

#### JWT 

This is the only auth type that seems to not allow use of the `authParams`. We can dig in to verify this is true and if so, add a 1st class `jwt.token` property for this case only.

```yaml
spring.pulsar.client.a12n.jwt:
  token
```
